---
jobs:
- name: build-docker-image
  public: true
  serial: true
  plan:
  - get: conc_docker_image
    trigger: true
  - put: docker-image
    params:
      build: conc_docker_image

resources:
- name: conc_docker_image
  type: git
  source:
    uri: https://github.com/robertwol/conc_docker_image.git
    branch: master

- name: docker-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    repository: {{docker-hub-image-resource}}
