---
jobs:
- name: remove_snapshots
  public: true
  serial: true
  plan:
  - get: resource-git
#  - get: timer
#    trigger: true
  - task: remove-snapshot-task
    config:
      platform: linux
      image: docker:///robertwol/hybdocker
      #inputs:
      #- name: resource-git
      #    path: .
      #run:
      #  path: ./run.sh
      run:
        path: resource-git/run.sh
        args: "test"
       #path: ls

resources:
- name: resource-git
  type: git
  source:
    uri: https://github.com/robertwol/conc_docker_image.git
    branch: master

#- name: timer
# type: time
#  source:
#    interval: 10m
